COMMON_DISEASES = [
    "Flu",
    "Cold",
    "Gastritis",
    "Migraine",
    "Allergy",
    "Hypertension",
    "Bronchitis",
    "Otitis",
    "Sinusitis",
    "Conjunctivitis",
    "Pneumonia",
    "Stomach ulcer",
    "Asthma",
    "Type 2 diabetes",
    "Psoriasis",
    "Hypothyroidism",
]

MEDIUM_DISEASES = [
    "Rheumatoid arthritis",
    "Crohn's disease",
    "Fibromyalgia",
    "Epilepsy",
    "Hodgkin's disease",
    "Diffuse non-Hodgkin lymphoma",
    "Chronic lymphocytic leukemia",
    "Chronic myeloid leukemia",
    "Anthrax",
    "Malaria",
    "Leishmaniasis",
    "Amyotrophic lateral sclerosis",
    "Multiple sclerosis",
    "Myasthenia",
    "Adult Still's disease",
    "Juvenile idiopathic arthritis",
    "Behcet's disease",
    "Osteogenesis imperfecta",
    "Congenital ichthyosis",
]

HARD_DISEASES = [
    "Lyme disease",
    "Systemic lupus erythematosus",
    "Sarcoidosis",
    "Addison's disease",
    "Guillain-Barre syndrome",
    "Cushing's disease",
    "Myasthenia gravis",
    "Wilson's disease",
    "Primary sclerosing cholangitis",
    "Granulomatosis with polyangiitis",
    "Multidrug-resistant tuberculosis",
    "Adrenal cortex carcinoma",
    "Waldenstrom macroglobulinemia",
    "Multiple myeloma",
    "Acute lymphoblastic leukemia",
    "Hairy cell leukemia",
    "Acute myeloid leukemia",
    "Myeloid sarcoma",
    "Idiopathic myelofibrosis",
    "Thalassemia",
    "Paroxysmal nocturnal hemoglobinuria",
    "Aplastic anemia",
    "Hemophilia",
    "Crimean-Congo hemorrhagic fever",
    "Evans syndrome",
    "Histiocytosis",
    "Primary immunodeficiencies",
    "Pompe disease",
    "Fabry disease",
    "Gaucher disease",
    "Mucopolysaccharidosis",
    "Porphyria",
    "Cystic fibrosis",
    "Familial Mediterranean fever",
    "Dravet syndrome",
    "Muscular dystrophy",
    "Glut1 deficiency syndrome",
    "Interstitial lung disease",
    "Idiopathic pulmonary arterial hypertension",
    "Pemphigus",
    "Cryopyrin-associated periodic syndromes",
    "Wegener's granulomatosis",
    "Takayasu's arteritis",
    "Microscopic polyangiitis",
    "Juvenile dermatomyositis",
    "Progressive systemic sclerosis",
    "Nasopharyngeal carcinoma",
    "Epidermolysis bullosa",
    "Pleural mesothelioma",
    "Retinoblastoma",
    "Malignant brain tumors",
]
