# Generated by Django 5.1 on 2024-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='patient',
        ),
        migrations.AddField(
            model_name='chat',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='patient_data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
