# Generated by Django 5.1 on 2024-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_chat_patient_chat_feedback_chat_is_finished_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
