# Generated by Django 5.1 on 2024-08-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chat',
            name='patient_responses',
            field=models.TextField(default=1, verbose_name='Предварительные ответы пациента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='patient_data',
            field=models.TextField(verbose_name='Данные пациента'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
    ]
