# Generated by Django 5.1 on 2024-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chat_options_alter_chat_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='correct_diagnosis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
